name: example
description: A new Flutter project.

publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adwaita: 
    git:
      url: git@github.com:supernova314/adwaita.git
  desktop_multi_window: ">=0.1.0 <1.0.0"
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  handy_window: ^0.3.1
  libadwaita:
    path: ../
  yaru_window: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/